In [4]:
#Create a simple array of numbers 0-11
arr = np.arange(12)
print("Original array:", arr)
reshaped = arr.reshape(3,4)
print("Reshaped (3x4):\n", reshaped)

#Indexing examples
print("first element: ", reshaped[0,0])
print("All rows, column 2:", reshaped[:,2])

#Reshape to 3 rows * 4 coloumns

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
first element:  0
All rows, column 2: [ 2  6 10]


In [11]:
import pandas as pd
from sklearn.datasets import load_iris

iris=load_iris(as_frame=True)
df=pd.concat([iris.data, pd.Series(iris.target, name='target')], axis=1)

#Map target numbers: species names
df['species'] = df['target'].map({i:n for i,n in enumerate(iris.target_names)})
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target species  
0       0  setosa  
1       0  setosa  
2       0  setosa  
3       0  setosa  
4       0  setosa

In [12]:
avg=df.groupby('species')['petal length (cm)'].mean()
print(avg)

species
setosa        1.462
versicolor    4.260
virginica     5.552
Name: petal length (cm), dtype: float64


In [ ]:
import matplotlib.pyplot as plt

avg.plot(kind='bar')
plt.